on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Github Action for LaTeX
        # You may pin to the exact commit or the version.
        # uses: xu-cheng/latex-action@dacf2cfbdd5fd768c2298cbdc9e105bd9ed7f293
        uses: xu-cheng/latex-action@v2
        with:
          # The root LaTeX file to be compiled
          root_file: shizun_ge_resume.tex
          # The working directory for the LaTeX engine
          # working_directory:
          # The LaTeX engine to be invoked
          # compiler: # optional, default is latexmk
          # Extra arguments to be passed to the LaTeX engine
          # args: # optional, default is -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          # [Deprecated] Install extra packages by tlmgr
          # extra_packages: # optional
          # Install extra packages by apk
          # extra_system_packages: texmf-dist-fontsextra # optional
          # Arbitrary bash codes to be executed before compiling LaTeX documents
          # pre_compile: # optional
          # Arbitrary bash codes to be executed after compiling LaTeX documents
          # post_compile: # optional
          # Instruct latexmk to enable --shell-escape
          # latexmk_shell_escape: # optional
          # Instruct latexmk to use LuaLaTeX
          # latexmk_use_lualatex: # optional
          # Instruct latexmk to use XeLaTeX
          latexmk_use_xelatex: true # optional
      - name: Upload Release Asset
        id: upload-release-asset  steps.create_release.outputs.upload_url
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: shizun_ge_resume.pdf
          asset_name: shizun_ge_resume
          asset_content_type: application/pdf
